version: '2'
services:
  db:
    image: mongo
    volumes:
      - ./mongo_data:/data/db
  web:
    build: .
    command: sh -c 'sleep 15; node server.js' 
    ports:
      - "3000:3000"
    depends_on:
      - db
